server:
  port: 8088
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/baiyun_db
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
